include:
  - jpo-utils/docker-compose.yml
  - docker-compose-ode.yml

services:
  mec-deposit:
    profiles:
      - all
      - mec_deposit_base
      - mec_deposit_full
    build:
      context: .
      dockerfile: Dockerfile
      args:
        MAVEN_GITHUB_TOKEN: ${MAVEN_GITHUB_TOKEN:?error}
        MAVEN_GITHUB_ORG: ${MAVEN_GITHUB_ORG:?error}
    image: jpo_mec_deposit:latest
    restart: ${RESTART_POLICY}
    ports:
      - "8082:8082"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2G
    depends_on:
      kafka:
        condition: service_healthy
        required: false
    environment:
      SPRING_PROFILES_ACTIVE: ${SPRING_PROFILES_ACTIVE:-docker}
      KAFKA_BOOTSTRAP_SERVERS: ${DOCKER_HOST_IP}:9092
      KAFKA_CONCURRENCY: ${KAFKA_CONCURRENCY}
      KAFKA_CONSUMER_GROUP_ID: ${KAFKA_CONSUMER_GROUP_ID}

      CONFLUENT_KEY: ${CONFLUENT_KEY}
      CONFLUENT_SECRET: ${CONFLUENT_SECRET}

      LOGGING_LEVEL: ${LOGGING_LEVEL}

      METRICS_ENABLED: ${METRICS_ENABLED}
      METRICS_KAFKA_TOPIC: ${METRICS_KAFKA_TOPIC}
      MQTT_SIGNATURE_VALIDATION_ENABLED: ${MQTT_SIGNATURE_VALIDATION_ENABLED}
      MQTT_SIGNATURE_VALIDATION_API_URL: ${MQTT_SIGNATURE_VALIDATION_API_URL}

      ETX_ENABLED: ${ETX_ENABLED}
      ETX_CERT_PATH: ${ETX_CERT_PATH}
      ETX_REGISTRATION_VENDOR: ${ETX_REGISTRATION_VENDOR}
      ETX_MQTT_VENDOR: ${ETX_MQTT_VENDOR}
      ETX_MQTT_MESSAGE_FORMAT: ${ETX_MQTT_MESSAGE_FORMAT}
      ETX_NETWORK_TYPE: ${ETX_NETWORK_TYPE}
      ETX_PARTNER_API_BASE_URI: ${ETX_PARTNER_API_BASE_URI}
      ETX_PARTNER_API_USERNAME: ${ETX_PARTNER_API_USERNAME}
      ETX_PARTNER_API_PASSWORD: ${ETX_PARTNER_API_PASSWORD}
      ETX_CLIENT_TYPE: ${ETX_CLIENT_TYPE}
      ETX_CLIENT_SUB_TYPE: ${ETX_CLIENT_SUB_TYPE}
      ETX_CACHE_REGISTRATION: ${ETX_CACHE_REGISTRATION}
      ETX_MEC_LATITUDE: ${ETX_MEC_LATITUDE}
      ETX_MEC_LONGITUDE: ${ETX_MEC_LONGITUDE}
      ETX_PUBLISH_RATE: ${ETX_PUBLISH_RATE}
      ETX_MQTT_USE_TLS: ${ETX_MQTT_USE_TLS}
      ETX_MQTT_USE_REGISTRATION: ${ETX_MQTT_USE_REGISTRATION}
      ETX_MQTT_REQUIRE_SESSION_ID: ${ETX_MQTT_REQUIRE_SESSION_ID}
      ETX_MQTT_BROKER_URI: ${ETX_MQTT_BROKER_URI}
      ETX_MQTT_CLIENT_ID: ${ETX_MQTT_CLIENT_ID}
      ETX_MQTT_BROKER_TYPE: ${ETX_MQTT_BROKER_TYPE}
      ETX_MQTT_DUAL_PUBLISH_ENABLED: ${ETX_MQTT_DUAL_PUBLISH_ENABLED}
      ETX_MQTT_DUAL_PUBLISH_TARGETS: ${ETX_MQTT_DUAL_PUBLISH_TARGETS}
      NMI_MQTT_ENABLED: ${NMI_MQTT_ENABLED}
      NMI_MQTT_BROKER_URI: ${NMI_MQTT_BROKER_URI}
      NMI_MQTT_CLIENT_ID: ${NMI_MQTT_CLIENT_ID}
      NMI_MQTT_QOS: ${NMI_MQTT_QOS}
      NMI_MQTT_PUBLISH_RATE: ${NMI_MQTT_PUBLISH_RATE}
      NMI_MQTT_PRECISION: ${NMI_MQTT_PRECISION}
      NMI_MQTT_CIRCUIT_BREAKER_FAILURE_THRESHOLD: ${NMI_MQTT_CIRCUIT_BREAKER_FAILURE_THRESHOLD}
      AV_MQTT_ENABLED: ${AV_MQTT_ENABLED}
      AV_MQTT_BROKER_URI: ${AV_MQTT_BROKER_URI}
      AV_MQTT_CLIENT_ID: ${AV_MQTT_CLIENT_ID}
      AV_MQTT_QOS: ${AV_MQTT_QOS}
      AV_MQTT_PUBLISH_RATE: ${AV_MQTT_PUBLISH_RATE}
      AV_MQTT_PRECISION: ${AV_MQTT_PRECISION}
      AV_MQTT_CIRCUIT_BREAKER_FAILURE_THRESHOLD: ${AV_MQTT_CIRCUIT_BREAKER_FAILURE_THRESHOLD}
      ETX_PARTNER_API_CLEAR_TIM_ENABLED: ${ETX_PARTNER_API_CLEAR_TIM_ENABLED}
      ETX_PARTNER_API_CLEAR_TIM_INTERVAL: ${ETX_PARTNER_API_CLEAR_TIM_INTERVAL}

      ETX_DEPOSITORS_STALE_MESSAGE_THRESHOLD: ${ETX_DEPOSITORS_STALE_MESSAGE_THRESHOLD}

      ETX_DEPOSITORS_BSM_MQTT_ENABLED: ${ETX_DEPOSITORS_BSM_MQTT_ENABLED}
      ETX_DEPOSITORS_BSM_MQTT_KAFKA_TOPIC: ${ETX_DEPOSITORS_BSM_MQTT_KAFKA_TOPIC}

      ETX_DEPOSITORS_PSM_MQTT_ENABLED: ${ETX_DEPOSITORS_PSM_MQTT_ENABLED}
      ETX_DEPOSITORS_PSM_MQTT_KAFKA_TOPIC: ${ETX_DEPOSITORS_PSM_MQTT_KAFKA_TOPIC}

      ETX_DEPOSITORS_SPAT_MQTT_ENABLED: ${ETX_DEPOSITORS_SPAT_MQTT_ENABLED}
      ETX_DEPOSITORS_SPAT_MQTT_KAFKA_TOPIC: ${ETX_DEPOSITORS_SPAT_MQTT_KAFKA_TOPIC}
      ETX_DEPOSITORS_SPAT_INTERSECTION_FILTER_ENABLED: ${ETX_DEPOSITORS_SPAT_INTERSECTION_FILTER_ENABLED}
      ETX_DEPOSITORS_SPAT_ALLOWED_INTERSECTIONS: ${ETX_DEPOSITORS_SPAT_ALLOWED_INTERSECTIONS}
      ETX_DEPOSITORS_SPAT_BLOCKED_INTERSECTIONS: ${ETX_DEPOSITORS_SPAT_BLOCKED_INTERSECTIONS}
      NMI_DEPOSITORS_SPAT_INTERSECTION_FILTER_ENABLED: ${NMI_DEPOSITORS_SPAT_INTERSECTION_FILTER_ENABLED}
      NMI_DEPOSITORS_SPAT_ALLOWED_INTERSECTIONS: ${NMI_DEPOSITORS_SPAT_ALLOWED_INTERSECTIONS}
      NMI_DEPOSITORS_SPAT_BLOCKED_INTERSECTIONS: ${NMI_DEPOSITORS_SPAT_BLOCKED_INTERSECTIONS}
      AV_DEPOSITORS_SPAT_INTERSECTION_FILTER_ENABLED: ${AV_DEPOSITORS_SPAT_INTERSECTION_FILTER_ENABLED}
      AV_DEPOSITORS_SPAT_ALLOWED_INTERSECTIONS: ${AV_DEPOSITORS_SPAT_ALLOWED_INTERSECTIONS}
      AV_DEPOSITORS_SPAT_BLOCKED_INTERSECTIONS: ${AV_DEPOSITORS_SPAT_BLOCKED_INTERSECTIONS}
      ETX_DEPOSITORS_TIM_MQTT_ENABLED: ${ETX_DEPOSITORS_TIM_MQTT_ENABLED}
      ETX_DEPOSITORS_TIM_MQTT_KAFKA_TOPIC: ${ETX_DEPOSITORS_TIM_MQTT_KAFKA_TOPIC}
      ETX_DEPOSITORS_TIM_API_ENABLED: ${ETX_DEPOSITORS_TIM_API_ENABLED}
      ETX_DEPOSITORS_TIM_API_KAFKA_TOPIC: ${ETX_DEPOSITORS_TIM_API_KAFKA_TOPIC}

      ETX_DEPOSITORS_MAP_MQTT_ENABLED: ${ETX_DEPOSITORS_MAP_MQTT_ENABLED}
      ETX_DEPOSITORS_MAP_MQTT_KAFKA_TOPIC: ${ETX_DEPOSITORS_MAP_MQTT_KAFKA_TOPIC}
      ETX_DEPOSITORS_MAP_API_ENABLED: ${ETX_DEPOSITORS_MAP_API_ENABLED}
      ETX_DEPOSITORS_MAP_API_KAFKA_TOPIC: ${ETX_DEPOSITORS_MAP_API_KAFKA_TOPIC}

      ETX_DEPOSITORS_SDSM_MQTT_ENABLED: ${ETX_DEPOSITORS_SDSM_MQTT_ENABLED}
      ETX_DEPOSITORS_SDSM_MQTT_KAFKA_TOPIC: ${ETX_DEPOSITORS_SDSM_MQTT_KAFKA_TOPIC}

      ETX_DEPOSITORS_GEOHASH_MQTT_ENABLED: ${ETX_DEPOSITORS_GEOHASH_MQTT_ENABLED}
      ETX_DEPOSITORS_GEOHASH_MQTT_KAFKA_TOPIC: ${ETX_DEPOSITORS_GEOHASH_MQTT_KAFKA_TOPIC}
      ETX_MQTT_BROKERS_ETX_DEPOSITORS_BSM_MQTT_ENABLED: ${ETX_MQTT_BROKERS_ETX_DEPOSITORS_BSM_MQTT_ENABLED}
      ETX_MQTT_BROKERS_ETX_DEPOSITORS_PSM_MQTT_ENABLED: ${ETX_MQTT_BROKERS_ETX_DEPOSITORS_PSM_MQTT_ENABLED}
      ETX_MQTT_BROKERS_ETX_DEPOSITORS_SPAT_MQTT_ENABLED: ${ETX_MQTT_BROKERS_ETX_DEPOSITORS_SPAT_MQTT_ENABLED}
      NMI_MQTT_BROKERS_NMI_DEPOSITORS_BSM_MQTT_ENABLED: ${NMI_MQTT_BROKERS_NMI_DEPOSITORS_BSM_MQTT_ENABLED}
      NMI_MQTT_BROKERS_NMI_DEPOSITORS_PSM_MQTT_ENABLED: ${NMI_MQTT_BROKERS_NMI_DEPOSITORS_PSM_MQTT_ENABLED}
      NMI_MQTT_BROKERS_NMI_DEPOSITORS_SPAT_MQTT_ENABLED: ${NMI_MQTT_BROKERS_NMI_DEPOSITORS_SPAT_MQTT_ENABLED}
      NMI_MQTT_BROKERS_NMI_DEPOSITORS_MAP_MQTT_ENABLED: ${NMI_MQTT_BROKERS_NMI_DEPOSITORS_MAP_MQTT_ENABLED}
      AV_MQTT_BROKERS_AV_DEPOSITORS_BSM_MQTT_ENABLED: ${AV_MQTT_BROKERS_AV_DEPOSITORS_BSM_MQTT_ENABLED}
      AV_MQTT_BROKERS_AV_DEPOSITORS_PSM_MQTT_ENABLED: ${AV_MQTT_BROKERS_AV_DEPOSITORS_PSM_MQTT_ENABLED}
      AV_MQTT_BROKERS_AV_DEPOSITORS_SPAT_MQTT_ENABLED: ${AV_MQTT_BROKERS_AV_DEPOSITORS_SPAT_MQTT_ENABLED}
      AV_MQTT_BROKERS_AV_DEPOSITORS_MAP_MQTT_ENABLED: ${AV_MQTT_BROKERS_AV_DEPOSITORS_MAP_MQTT_ENABLED}
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    volumes:
      - ./resources:/home/resources
