include:
  - jpo-utils/docker-compose.yml
  - docker-compose-ode.yml

services:
  mec_deposit:
    profiles:
      - all
      - mec_deposit_base
      - deduplicator
    build:
      context: .
      dockerfile: Dockerfile
    image: jpo_mec_deposit:latest
    restart: ${RESTART_POLICY}
    ports:
      - "8082:8082"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2G
    environment:
      SPRING_PROFILES_ACTIVE: docker
      KAFKA_BOOTSTRAP_SERVERS: ${DOCKER_HOST_IP:?error}:9092
      LOGGING_LEVEL: ${LOGGING_LEVEL}

      # TODO: implement feature flags
      IMP_ENABLED: ${IMP_ENABLED}

      IMP_VENDOR: ${IMP_VENDOR}
      IMP_NETWORK_TYPE: ${IMP_NETWORK_TYPE}
      IMP_CACHE_REGISTRATION: ${IMP_CACHE_REGISTRATION}
      IMP_CERT_PATH: ${IMP_CERT_PATH}

      IMP_MQTT_VENDOR: ${IMP_MQTT_VENDOR}
      IMP_CLIENT_TYPE: ${IMP_CLIENT_TYPE}
      IMP_CLIENT_SUB_TYPE: ${IMP_CLIENT_SUB_TYPE}

      IMP_PARTNER_API_BASE_URI: ${IMP_PARTNER_API_BASE_URI}
      IMP_PARTNER_USER: ${IMP_PARTNER_USER}
      IMP_PARTNER_PASS: ${IMP_PARTNER_PASS}
      IMP_MEC_LATITUDE: ${IMP_MEC_LATITUDE}
      IMP_MEC_LONGITUDE: ${IMP_MEC_LONGITUDE}
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    volumes:
      - ${DOCKER_SHARED_VOLUME}/resources:/home/resources
