include:
  - jpo-utils/docker-compose.yml
  - docker-compose-ode.yml

services:
  mec_deposit:
    profiles:
      - all
      - mec_deposit_base
      - deduplicator
    build:
      context: .
      dockerfile: Dockerfile
    image: jpo_mec_deposit:latest
    restart: ${RESTART_POLICY}
    ports:
      - "8082:8082"
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 2G
    environment:
      SPRING_PROFILES_ACTIVE: docker
      KAFKA_BOOTSTRAP_SERVERS: ${DOCKER_HOST_IP:?error}:9092
      LOGGING_LEVEL: ${LOGGING_LEVEL}

      ETX_ENABLED: ${ETX_ENABLED}
      ETX_CERT_PATH: ${ETX_CERT_PATH}
      ETX_VENDOR: ${ETX_VENDOR}
      ETX_MQTT_VENDOR: ${ETX_MQTT_VENDOR}
      ETX_MQTT_MESSAGE_FORMAT: ${ETX_MQTT_MESSAGE_FORMAT}
      ETX_NETWORK_TYPE: ${ETX_NETWORK_TYPE}
      ETX_PARTNER_API_BASE_URI: ${ETX_PARTNER_API_BASE_URI}
      ETX_PARTNER_API_USERNAME: ${ETX_PARTNER_API_USERNAME}
      ETX_PARTNER_API_PASSWORD: ${ETX_PARTNER_API_PASSWORD}
      ETX_CLIENT_TYPE: ${ETX_CLIENT_TYPE}
      ETX_CLIENT_SUB_TYPE: ${ETX_CLIENT_SUB_TYPE}
      ETX_CACHE_REGISTRATION: ${ETX_CACHE_REGISTRATION}
      ETX_MEC_LATITUDE: ${ETX_MEC_LATITUDE}
      ETX_MEC_LONGITUDE: ${ETX_MEC_LONGITUDE}
      ETX_PUBLISH_RATE: ${ETX_PUBLISH_RATE}
      ETX_PARTNER_API_CLEAR_TIM_ENABLED: ${ETX_PARTNER_API_CLEAR_TIM_ENABLED}
      ETX_PARTNER_API_CLEAR_TIM_INTERVAL: ${ETX_PARTNER_API_CLEAR_TIM_INTERVAL}

      ETX_DEPOSITORS_BSM_MQTT_ENABLED: ${ETX_DEPOSITORS_BSM_MQTT_ENABLED}
      ETX_DEPOSITORS_BSM_MQTT_KAFKA_TOPIC: ${ETX_DEPOSITORS_BSM_MQTT_KAFKA_TOPIC}
      ETX_DEPOSITORS_SPAT_MQTT_ENABLED: ${ETX_DEPOSITORS_SPAT_MQTT_ENABLED}
      ETX_DEPOSITORS_SPAT_MQTT_KAFKA_TOPIC: ${ETX_DEPOSITORS_SPAT_MQTT_KAFKA_TOPIC}
      ETX_DEPOSITORS_TIM_MQTT_ENABLED: ${ETX_DEPOSITORS_TIM_MQTT_ENABLED}
      ETX_DEPOSITORS_TIM_MQTT_KAFKA_TOPIC: ${ETX_DEPOSITORS_TIM_MQTT_KAFKA_TOPIC}
      ETX_DEPOSITORS_TIM_API_ENABLED: ${ETX_DEPOSITORS_TIM_API_ENABLED}
      ETX_DEPOSITORS_TIM_API_KAFKA_TOPIC: ${ETX_DEPOSITORS_TIM_API_KAFKA_TOPIC}
      ETX_DEPOSITORS_MAP_MQTT_ENABLED: ${ETX_DEPOSITORS_MAP_MQTT_ENABLED}
      ETX_DEPOSITORS_MAP_MQTT_KAFKA_TOPIC: ${ETX_DEPOSITORS_MAP_MQTT_KAFKA_TOPIC}
      ETX_DEPOSITORS_MAP_API_ENABLED: ${ETX_DEPOSITORS_MAP_API_ENABLED}
      ETX_DEPOSITORS_MAP_API_KAFKA_TOPIC: ${ETX_DEPOSITORS_MAP_API_KAFKA_TOPIC}
    logging:
      options:
        max-size: "10m"
        max-file: "5"
    volumes:
      - ${DOCKER_SHARED_VOLUME}/resources:/home/resources
