spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: mec-deposit-consumer
imp:
  mqtt:
    subscriptions:
      - topic: "vzimp/1/ClientInfo"
      # Add more topics as needed
    qos: 1
