#General Properties
#==================
groupId: ^project.groupId^
artifactId: ^project.artifactId^
version: ^project.version^
server.port: 8082

# Depositor specific properties
depositor:
  imp:
    enabled: true
    vendor: ${IMP_VENDOR}
    network-type: ${IMP_NETWORK_TYPE}
    cache-registration: ${IMP_CACHE_REGISTRATION}
    certificate-path: ${IMP_CERT_PATH}
    client-type: ${IMP_CLIENT_TYPE}
    client-sub-type: ${IMP_CLIENT_SUB_TYPE}
    partner-api:
      base-uri: ${IMP_PARTNER_API_BASE_URI}
      user: ${IMP_PARTNER_USER}
      pass: ${IMP_PARTNER_PASS}

      # used for the partner api registration to determine the MEC location
      mec-latitude: ${IMP_MEC_LATITUDE}
      mec-longitude: ${IMP_MEC_LONGITUDE}

      # these depositors are not using mqtt but rather the partner api - HIGHER LATENCY
      depositors:
        map:
          source-kafka-topic: "topic.OdeMapJson"
          distribution-type: "Targeted"
        tim:
          source-kafka-topic: "topic.OdeTimJsonTMCFiltered"
          distribution-type: "Broadcast"

    mqtt:
      qos: 0
      max-inflight: 10
      vendor: ${IMP_MQTT_VENDOR}
      message-format: j2735
      depositors:
        bsm:
          source-kafka-topic: "topic.OdeBsmJson"
        spat:
          source-kafka-topic: "topic.OdeSpatJson"
        tim:
          source-kafka-topic: "topic.OdeTimJson"
      subscriptions:
        - "vzimp/1/ClientInfo"

# microservice actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 8082

logging:
  level:
    root: INFO
    org.springframework.web: WARN
    guru.springframework.controllers: WARN
    org.springframework.integration.mqtt: INFO
    us.dot.its.jpo.ode.mec.deposit: ${LOGGING_LEVEL:DEBUG}
    org.apache.kafka: WARN

# Spring boot properties
spring:
  profiles:
    default: "none"
    active: ${SPRING_PROFILES_ACTIVE:docker}
  kafka:
    bootstrap-servers: ${KAFKA_BOOTSTRAP_SERVERS}
    consumer:
      group-id: jpo-mec-deposit
      fetch-min-size: 1
      fetch-max-wait: 50
      max-poll-records: 500
      auto-offset-reset: earliest
      enable-auto-commit: true
      auto-commit-interval: 100
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
    listener:
      ack-mode: BATCH
      poll-timeout: 1
      idle-event-interval: 1
      idle-between-polls: 0
  config:
    import:
      - classpath:application-confluent.yaml
