#General Properties
#==================
groupId: ^project.groupId^
artifactId: ^project.artifactId^
version: ^project.version^
server.port: 8082

# microservice actuator
management:
  endpoints:
    web:
      exposure:
        include: "*"
  server:
    port: 8082

# Kafka properties
spring:
  kafka:
    consumer:
      group-id: jpo-mec-deposit
      fetch-min-size: 1
      fetch-max-wait: 50
      max-poll-records: 500
      auto-offset-reset: latest
      enable-auto-commit: true
      auto-commit-interval: 100
    listener:
      ack-mode: BATCH
      poll-timeout: 100
    bootstrap-servers: ${BOOTSTRAP_SERVER:localhost:9092}

logging:
  level:
    root: INFO
    org.springframework.web: WARN
    guru.springframework.controllers: WARN
    org.springframework.kafka: WARN
    org.apache.kafka: WARN
    us.dot.its.jpo.ode.mec.deposit: ${LOGGING_LEVEL:DEBUG}
