#General Properties
#==================
groupId: ^project.groupId^
artifactId: ^project.artifactId^
version: ^project.version^
server.port: 8082

# Kafka properties
spring:
  kafka:
    consumer:
      group-id: jpo-mec-deposit
    bootstrap-servers: ${BOOTSTRAP_SERVER:localhost:9092}

logging:
  level:
    root: INFO
    org.springframework.web: WARN
    guru.springframework.controllers: WARN
    org.springframework.kafka: WARN
    org.apache.kafka: WARN
    us.dot.its.jpo.ode.mec.deposit: ${LOGGING_LEVEL:DEBUG}
